// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
)

type Entry struct {
	ID         string
	ProjectID  int64
	CreatorID  sql.NullInt64
	Content    string
	DurationMs int64
	StartedAt  sql.NullInt64
	EndedAt    sql.NullInt64
	EntryType  string
	IsBillable int64
	CreatedAt  int64
	UpdatedAt  int64
}

type EntryTag struct {
	EntryID   string
	Tag       string
	CreatedAt int64
}

type Person struct {
	ID        int64
	Email     string
	Name      string
	CreatedAt int64
	UpdatedAt int64
}

type Project struct {
	ID        int64
	Name      string
	Company   sql.NullString
	IsHidden  int64
	Position  int64
	CreatedAt int64
	UpdatedAt int64
}

type Timer struct {
	ProjectID int64
	StartedAt int64
	CreatedAt int64
	UpdatedAt int64
}
