// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: data/models.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Entry_Type int32

const (
	Entry_CHORE Entry_Type = 0
	Entry_FUN   Entry_Type = 1
	Entry_WORK  Entry_Type = 2
)

// Enum value maps for Entry_Type.
var (
	Entry_Type_name = map[int32]string{
		0: "CHORE",
		1: "FUN",
		2: "WORK",
	}
	Entry_Type_value = map[string]int32{
		"CHORE": 0,
		"FUN":   1,
		"WORK":  2,
	}
)

func (x Entry_Type) Enum() *Entry_Type {
	p := new(Entry_Type)
	*p = x
	return p
}

func (x Entry_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Entry_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_data_models_proto_enumTypes[0].Descriptor()
}

func (Entry_Type) Type() protoreflect.EnumType {
	return &file_data_models_proto_enumTypes[0]
}

func (x Entry_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Entry_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Entry_Type(num)
	return nil
}

// Deprecated: Use Entry_Type.Descriptor instead.
func (Entry_Type) EnumDescriptor() ([]byte, []int) {
	return file_data_models_proto_rawDescGZIP(), []int{1, 0}
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Company       *string                `protobuf:"bytes,2,opt,name=company" json:"company,omitempty"`
	Hide          *bool                  `protobuf:"varint,3,opt,name=hide" json:"hide,omitempty"`
	Sha           *string                `protobuf:"bytes,4,opt,name=sha" json:"sha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_data_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_data_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_data_models_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Project) GetCompany() string {
	if x != nil && x.Company != nil {
		return *x.Company
	}
	return ""
}

func (x *Project) GetHide() bool {
	if x != nil && x.Hide != nil {
		return *x.Hide
	}
	return false
}

func (x *Project) GetSha() string {
	if x != nil && x.Sha != nil {
		return *x.Sha
	}
	return ""
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Duration      *int64                 `protobuf:"varint,2,req,name=duration" json:"duration,omitempty"`
	Content       *string                `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	Creator       *Person                `protobuf:"bytes,4,opt,name=creator" json:"creator,omitempty"`
	Started       *int64                 `protobuf:"varint,5,opt,name=started" json:"started,omitempty"`
	Ended         *int64                 `protobuf:"varint,6,opt,name=ended" json:"ended,omitempty"`
	Type          *Entry_Type            `protobuf:"varint,7,opt,name=type,enum=data.Entry_Type,def=2" json:"type,omitempty"`
	Project       *Project               `protobuf:"bytes,8,opt,name=project" json:"project,omitempty"`
	Billable      *bool                  `protobuf:"varint,9,opt,name=billable" json:"billable,omitempty"`
	Tags          []string               `protobuf:"bytes,10,rep,name=tags" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Entry fields.
const (
	Default_Entry_Type = Entry_WORK
)

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_data_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_data_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_data_models_proto_rawDescGZIP(), []int{1}
}

func (x *Entry) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Entry) GetDuration() int64 {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return 0
}

func (x *Entry) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *Entry) GetCreator() *Person {
	if x != nil {
		return x.Creator
	}
	return nil
}

func (x *Entry) GetStarted() int64 {
	if x != nil && x.Started != nil {
		return *x.Started
	}
	return 0
}

func (x *Entry) GetEnded() int64 {
	if x != nil && x.Ended != nil {
		return *x.Ended
	}
	return 0
}

func (x *Entry) GetType() Entry_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Default_Entry_Type
}

func (x *Entry) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *Entry) GetBillable() bool {
	if x != nil && x.Billable != nil {
		return *x.Billable
	}
	return false
}

func (x *Entry) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Person struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *string                `protobuf:"bytes,1,req,name=email" json:"email,omitempty"`
	Name          *string                `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_data_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_data_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_data_models_proto_rawDescGZIP(), []int{2}
}

func (x *Person) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *Person) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type Timer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,req,name=project" json:"project,omitempty"`
	Started       *int64                 `protobuf:"varint,2,req,name=started" json:"started,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timer) Reset() {
	*x = Timer{}
	mi := &file_data_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timer) ProtoMessage() {}

func (x *Timer) ProtoReflect() protoreflect.Message {
	mi := &file_data_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timer.ProtoReflect.Descriptor instead.
func (*Timer) Descriptor() ([]byte, []int) {
	return file_data_models_proto_rawDescGZIP(), []int{3}
}

func (x *Timer) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *Timer) GetStarted() int64 {
	if x != nil && x.Started != nil {
		return *x.Started
	}
	return 0
}

var File_data_models_proto protoreflect.FileDescriptor

const file_data_models_proto_rawDesc = "" +
	"\n" +
	"\x11data/models.proto\x12\x04data\"]\n" +
	"\aProject\x12\x12\n" +
	"\x04name\x18\x01 \x02(\tR\x04name\x12\x18\n" +
	"\acompany\x18\x02 \x01(\tR\acompany\x12\x12\n" +
	"\x04hide\x18\x03 \x01(\bR\x04hide\x12\x10\n" +
	"\x03sha\x18\x04 \x01(\tR\x03sha\"\xd0\x02\n" +
	"\x05Entry\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\tR\x02id\x12\x1a\n" +
	"\bduration\x18\x02 \x02(\x03R\bduration\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12&\n" +
	"\acreator\x18\x04 \x01(\v2\f.data.PersonR\acreator\x12\x18\n" +
	"\astarted\x18\x05 \x01(\x03R\astarted\x12\x14\n" +
	"\x05ended\x18\x06 \x01(\x03R\x05ended\x12*\n" +
	"\x04type\x18\a \x01(\x0e2\x10.data.Entry.Type:\x04WORKR\x04type\x12'\n" +
	"\aproject\x18\b \x01(\v2\r.data.ProjectR\aproject\x12\x1a\n" +
	"\bbillable\x18\t \x01(\bR\bbillable\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\"$\n" +
	"\x04Type\x12\t\n" +
	"\x05CHORE\x10\x00\x12\a\n" +
	"\x03FUN\x10\x01\x12\b\n" +
	"\x04WORK\x10\x02\"2\n" +
	"\x06Person\x12\x14\n" +
	"\x05email\x18\x01 \x02(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x02(\tR\x04name\"J\n" +
	"\x05Timer\x12'\n" +
	"\aproject\x18\x01 \x02(\v2\r.data.ProjectR\aproject\x12\x18\n" +
	"\astarted\x18\x02 \x02(\x03R\astartedB\bZ\x06./data"

var (
	file_data_models_proto_rawDescOnce sync.Once
	file_data_models_proto_rawDescData []byte
)

func file_data_models_proto_rawDescGZIP() []byte {
	file_data_models_proto_rawDescOnce.Do(func() {
		file_data_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_models_proto_rawDesc), len(file_data_models_proto_rawDesc)))
	})
	return file_data_models_proto_rawDescData
}

var file_data_models_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_data_models_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_data_models_proto_goTypes = []any{
	(Entry_Type)(0), // 0: data.Entry.Type
	(*Project)(nil), // 1: data.Project
	(*Entry)(nil),   // 2: data.Entry
	(*Person)(nil),  // 3: data.Person
	(*Timer)(nil),   // 4: data.Timer
}
var file_data_models_proto_depIdxs = []int32{
	3, // 0: data.Entry.creator:type_name -> data.Person
	0, // 1: data.Entry.type:type_name -> data.Entry.Type
	1, // 2: data.Entry.project:type_name -> data.Project
	1, // 3: data.Timer.project:type_name -> data.Project
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_data_models_proto_init() }
func file_data_models_proto_init() {
	if File_data_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_models_proto_rawDesc), len(file_data_models_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_models_proto_goTypes,
		DependencyIndexes: file_data_models_proto_depIdxs,
		EnumInfos:         file_data_models_proto_enumTypes,
		MessageInfos:      file_data_models_proto_msgTypes,
	}.Build()
	File_data_models_proto = out.File
	file_data_models_proto_goTypes = nil
	file_data_models_proto_depIdxs = nil
}
